apiVersion: v1
kind: Service
metadata:
  labels:
    app: goserver
  name: goserver
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9000
  selector:
    app: goserver
  type: NodePort
