apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontendserver
  name: frontendserver
  namespace: demo2server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: frontendserver
  type: NodePort
